import type { Metadata } from "next";
import { Roboto, Montserrat } from "next/font/google";
import "./globals.css";

import Head from "@/components/Header"

const roboto = Roboto({
  subsets:['latin'],
  variable:'--font-roboto'
})

const montserrat = Montserrat({
  subsets:['latin'],
  variable:'--font-montserrat'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${montserrat.variable} font-main`}
      >
        <Head/>
        {children}
      </body>
    </html>
  );
}
